"use strict";

var ComparisonMatchExpression = require('./ComparisonMatchExpression');

// Autogenerated by cport.py on 2013-09-17 14:37
var EqualityMatchExpression = module.exports = function EqualityMatchExpression(){
	base.call(this,'EQ');
}, klass = EqualityMatchExpression, base =  ComparisonMatchExpression, proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});

/**
 *
 * Return a new instance of this class, with fields set the same as ourself
 * @method shallowClone
 * @param
 *
 */
proto.shallowClone = function shallowClone( /*  */ ){
	var e = new EqualityMatchExpression();
	e.init ( this.path(), this._rhs );
	
	if ( this.getTag() ) {
		e.setTag(this.getTag().clone());
	}
	return e;
};
